### ISSUE TITLE
how should we impliment vpcs

### ISSUE THREAD

**Issue by gregf** [test-kitchen/kitchen-digitalocean#75]
For those of you planning on making use of vpcs in your tests, how do you want it to work in kitchen-digitalocean? Looking for feedback before implementing it.

**Comment by zetas** [comment]
I was actually just trying to update my cookbooks to use the new VPC feature because I want to test that some of my VPC based services are available from the nodes spun up by chef. I'd like it to work just like the VPC id selector in the AWS module, effectively: `vpc_id: my-vpc-id` in the yaml would be just fine. I don't think it's necessary to handle creating VPC's and stuff from test kitchen but that's just my 2cp.

**Comment by gregf** [comment]
I'll do t his and cut a release sometime this week. Been super busy sorry.

**Comment by zetas** [comment]
No need to apologize friend. You do great work, thanks for maintaining this amazing repo!

**Comment by gregf** [comment]
This is ready to rock in 0.11.0. Please open a issue if there are any issues.
